"""Revert to old file name

Revision ID: 212c4ecaab8a
Revises: fd9bff5f55e2
Create Date: 2022-01-11 21:45:22.162685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212c4ecaab8a'
down_revision = 'fd9bff5f55e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=60), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.VARCHAR(length=60), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
