"""Add uuid column to product and user models

Revision ID: 2b9700c80b8b
Revises: bf54c5b5c712
Create Date: 2022-01-08 18:26:56.740015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b9700c80b8b'
down_revision = 'bf54c5b5c712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prod_uuid', sa.String(length=36), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_uuid', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_uuid')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('prod_uuid')

    # ### end Alembic commands ###
