"""empty message

Revision ID: 78d95d3656f8
Revises: 5a2070845f8b
Create Date: 2022-01-10 13:19:34.947443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78d95d3656f8'
down_revision = '5a2070845f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_cart_cart_id', 'cart', ['cart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###
