"""Delete cart model

Revision ID: be5a86886faf
Revises: 78d95d3656f8
Create Date: 2022-01-11 16:07:26.872253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5a86886faf'
down_revision = '78d95d3656f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.drop_index('ix_cart_id')

    op.drop_table('cart')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_cart_cart_id', type_='foreignkey')
        batch_op.drop_column('cart_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_cart_cart_id', 'cart', ['cart_id'], ['id'])

    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.create_index('ix_cart_id', ['id'], unique=False)

    # ### end Alembic commands ###
