"""Introduce image_path column

Revision ID: fd9bff5f55e2
Revises: 1079166d8059
Create Date: 2022-01-11 21:34:42.743715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9bff5f55e2'
down_revision = '1079166d8059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=60), nullable=True))
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
